# Generated by Django 3.2.8 on 2021-10-05 18:21

import Submission.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Class', '0002_alter_classactivity_created_date_and_more'),
        ('User', '0002_auto_20211005_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('graded', models.IntegerField(validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(100)])),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Class.classactivity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.student')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file', models.FileField(upload_to=Submission.models.file_directory_path)),
                ('student_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Submission.submission')),
            ],
        ),
    ]
