# Generated by Django 3.2.8 on 2021-10-08 12:00

import Activity.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0002_auto_20211005_1914'),
        ('Class', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('deadline_date', models.DateTimeField(blank=True, null=True, validators=[Activity.models.check_submitted_date])),
                ('is_submit', models.BooleanField(default=False)),
                ('is_assignment', models.BooleanField(default=False)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Class.class')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('submitted_date', models.DateTimeField(blank=True, null=True)),
                ('graded', models.IntegerField(validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(100)])),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Activity.activity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.student')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file', models.FileField(upload_to=Activity.models.file_directory_submission_path)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Activity.submission')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file', models.FileField(upload_to=Activity.models.file_directory_activity_path)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Activity.activity')),
            ],
        ),
    ]
