# Generated by Django 4.0.dev20210910103700 on 2021-10-04 12:49

import Class.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classactivity',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='classactivity',
            name='submitted_date',
            field=models.DateTimeField(blank=True, null=True, validators=[Class.models.check_submitted_date]),
        ),
    ]
