# Generated by Django 3.2.8 on 2021-10-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class', '0002_alter_classactivity_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classactivity',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
