# Generated by Django 3.2.8 on 2021-11-07 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20211005_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='profile_image',
            field=models.ImageField(blank=True, default='user-default.png', null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(blank=True, default='user-default.png', null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='profile_image',
            field=models.ImageField(blank=True, default='user-default.png', null=True, upload_to='profiles/'),
        ),
    ]
