# Generated by Django 3.2.8 on 2021-11-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20211111_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='DOB',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
