# Generated by Django 3.2.8 on 2021-11-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_alter_student_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='DOB',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='DOB',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
